{% set name = "datastock" %}
{% set version = "0.0.42" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datastock-{{ version }}.tar.gz
  sha256: 5595254810680275f2e3a13f3823b07472d2afa374694bfb45aeba8479f5204b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy
    - astropy-base

test:
  imports:
    - datastock
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ToFuProject/datastock
  summary: A python library for generic class and data handling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
