{% set name = "datastock" %}
{% set version = "0.0.39" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datastock-{{ version }}.tar.gz
  sha256: f0a080ce5fc66b860ffac3077d544ec17f41af0da524effe6953c38bad2c1de3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.7
    - scipy
    - astropy

test:
  imports:
    - datastock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/datastock
  summary: A python library for generic class and data handling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
