{% set name = "datastock" %}
{% set version = "0.0.41" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datastock-{{ version }}.tar.gz
  sha256: 12ea5cc657f3df27c719483f6a1dacc660e29adf195d6929573baf239b61952b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.7
    - scipy
    - astropy

test:
  imports:
    - datastock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/datastock
  summary: A python library for generic class and data handling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
