{% set name = "datastock" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datastock-{{ version }}.tar.gz
  sha256: de5dca11640488d81324196ef76a1e759afa9b757ab6ba654c279ca9071d5a9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - datastock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/datastock
  summary: A python library for generic class and data handling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
